# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/admin/workSpace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/admin/workSpace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/admin/workSpace/CMakeFiles /home/admin/workSpace/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/admin/workSpace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named JKYi

# Build rule for target.
JKYi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JKYi
.PHONY : JKYi

# fast build rule for target.
JKYi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/build
.PHONY : JKYi/fast

#=============================================================================
# Target rules for targets named my_http_server

# Build rule for target.
my_http_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_http_server
.PHONY : my_http_server

# fast build rule for target.
my_http_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/build
.PHONY : my_http_server/fast

#=============================================================================
# Target rules for targets named test_ws_client

# Build rule for target.
test_ws_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ws_client
.PHONY : test_ws_client

# fast build rule for target.
test_ws_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_client.dir/build.make CMakeFiles/test_ws_client.dir/build
.PHONY : test_ws_client/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_env

# Build rule for target.
test_env: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_env
.PHONY : test_env

# fast build rule for target.
test_env/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/build
.PHONY : test_env/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_application

# Build rule for target.
test_application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_application
.PHONY : test_application

# fast build rule for target.
test_application/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/build
.PHONY : test_application/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test_ws_server

# Build rule for target.
test_ws_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ws_server
.PHONY : test_ws_server

# fast build rule for target.
test_ws_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_server.dir/build.make CMakeFiles/test_ws_server.dir/build
.PHONY : test_ws_server/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named test_daemon

# Build rule for target.
test_daemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_daemon
.PHONY : test_daemon

# fast build rule for target.
test_daemon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/build
.PHONY : test_daemon/fast

JKYi/address.o: JKYi/address.cc.o

.PHONY : JKYi/address.o

# target to build an object file
JKYi/address.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/address.cc.o
.PHONY : JKYi/address.cc.o

JKYi/address.i: JKYi/address.cc.i

.PHONY : JKYi/address.i

# target to preprocess a source file
JKYi/address.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/address.cc.i
.PHONY : JKYi/address.cc.i

JKYi/address.s: JKYi/address.cc.s

.PHONY : JKYi/address.s

# target to generate assembly for a file
JKYi/address.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/address.cc.s
.PHONY : JKYi/address.cc.s

JKYi/application.o: JKYi/application.cc.o

.PHONY : JKYi/application.o

# target to build an object file
JKYi/application.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/application.cc.o
.PHONY : JKYi/application.cc.o

JKYi/application.i: JKYi/application.cc.i

.PHONY : JKYi/application.i

# target to preprocess a source file
JKYi/application.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/application.cc.i
.PHONY : JKYi/application.cc.i

JKYi/application.s: JKYi/application.cc.s

.PHONY : JKYi/application.s

# target to generate assembly for a file
JKYi/application.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/application.cc.s
.PHONY : JKYi/application.cc.s

JKYi/bytearray.o: JKYi/bytearray.cc.o

.PHONY : JKYi/bytearray.o

# target to build an object file
JKYi/bytearray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/bytearray.cc.o
.PHONY : JKYi/bytearray.cc.o

JKYi/bytearray.i: JKYi/bytearray.cc.i

.PHONY : JKYi/bytearray.i

# target to preprocess a source file
JKYi/bytearray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/bytearray.cc.i
.PHONY : JKYi/bytearray.cc.i

JKYi/bytearray.s: JKYi/bytearray.cc.s

.PHONY : JKYi/bytearray.s

# target to generate assembly for a file
JKYi/bytearray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/bytearray.cc.s
.PHONY : JKYi/bytearray.cc.s

JKYi/config.o: JKYi/config.cc.o

.PHONY : JKYi/config.o

# target to build an object file
JKYi/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/config.cc.o
.PHONY : JKYi/config.cc.o

JKYi/config.i: JKYi/config.cc.i

.PHONY : JKYi/config.i

# target to preprocess a source file
JKYi/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/config.cc.i
.PHONY : JKYi/config.cc.i

JKYi/config.s: JKYi/config.cc.s

.PHONY : JKYi/config.s

# target to generate assembly for a file
JKYi/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/config.cc.s
.PHONY : JKYi/config.cc.s

JKYi/daemon.o: JKYi/daemon.cc.o

.PHONY : JKYi/daemon.o

# target to build an object file
JKYi/daemon.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/daemon.cc.o
.PHONY : JKYi/daemon.cc.o

JKYi/daemon.i: JKYi/daemon.cc.i

.PHONY : JKYi/daemon.i

# target to preprocess a source file
JKYi/daemon.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/daemon.cc.i
.PHONY : JKYi/daemon.cc.i

JKYi/daemon.s: JKYi/daemon.cc.s

.PHONY : JKYi/daemon.s

# target to generate assembly for a file
JKYi/daemon.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/daemon.cc.s
.PHONY : JKYi/daemon.cc.s

JKYi/env.o: JKYi/env.cc.o

.PHONY : JKYi/env.o

# target to build an object file
JKYi/env.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/env.cc.o
.PHONY : JKYi/env.cc.o

JKYi/env.i: JKYi/env.cc.i

.PHONY : JKYi/env.i

# target to preprocess a source file
JKYi/env.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/env.cc.i
.PHONY : JKYi/env.cc.i

JKYi/env.s: JKYi/env.cc.s

.PHONY : JKYi/env.s

# target to generate assembly for a file
JKYi/env.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/env.cc.s
.PHONY : JKYi/env.cc.s

JKYi/fdmanager.o: JKYi/fdmanager.cc.o

.PHONY : JKYi/fdmanager.o

# target to build an object file
JKYi/fdmanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/fdmanager.cc.o
.PHONY : JKYi/fdmanager.cc.o

JKYi/fdmanager.i: JKYi/fdmanager.cc.i

.PHONY : JKYi/fdmanager.i

# target to preprocess a source file
JKYi/fdmanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/fdmanager.cc.i
.PHONY : JKYi/fdmanager.cc.i

JKYi/fdmanager.s: JKYi/fdmanager.cc.s

.PHONY : JKYi/fdmanager.s

# target to generate assembly for a file
JKYi/fdmanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/fdmanager.cc.s
.PHONY : JKYi/fdmanager.cc.s

JKYi/fiber.o: JKYi/fiber.cc.o

.PHONY : JKYi/fiber.o

# target to build an object file
JKYi/fiber.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/fiber.cc.o
.PHONY : JKYi/fiber.cc.o

JKYi/fiber.i: JKYi/fiber.cc.i

.PHONY : JKYi/fiber.i

# target to preprocess a source file
JKYi/fiber.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/fiber.cc.i
.PHONY : JKYi/fiber.cc.i

JKYi/fiber.s: JKYi/fiber.cc.s

.PHONY : JKYi/fiber.s

# target to generate assembly for a file
JKYi/fiber.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/fiber.cc.s
.PHONY : JKYi/fiber.cc.s

JKYi/hook.o: JKYi/hook.cc.o

.PHONY : JKYi/hook.o

# target to build an object file
JKYi/hook.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/hook.cc.o
.PHONY : JKYi/hook.cc.o

JKYi/hook.i: JKYi/hook.cc.i

.PHONY : JKYi/hook.i

# target to preprocess a source file
JKYi/hook.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/hook.cc.i
.PHONY : JKYi/hook.cc.i

JKYi/hook.s: JKYi/hook.cc.s

.PHONY : JKYi/hook.s

# target to generate assembly for a file
JKYi/hook.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/hook.cc.s
.PHONY : JKYi/hook.cc.s

JKYi/http/http.o: JKYi/http/http.cc.o

.PHONY : JKYi/http/http.o

# target to build an object file
JKYi/http/http.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http.cc.o
.PHONY : JKYi/http/http.cc.o

JKYi/http/http.i: JKYi/http/http.cc.i

.PHONY : JKYi/http/http.i

# target to preprocess a source file
JKYi/http/http.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http.cc.i
.PHONY : JKYi/http/http.cc.i

JKYi/http/http.s: JKYi/http/http.cc.s

.PHONY : JKYi/http/http.s

# target to generate assembly for a file
JKYi/http/http.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http.cc.s
.PHONY : JKYi/http/http.cc.s

JKYi/http/http11_parser.rl.o: JKYi/http/http11_parser.rl.cc.o

.PHONY : JKYi/http/http11_parser.rl.o

# target to build an object file
JKYi/http/http11_parser.rl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http11_parser.rl.cc.o
.PHONY : JKYi/http/http11_parser.rl.cc.o

JKYi/http/http11_parser.rl.i: JKYi/http/http11_parser.rl.cc.i

.PHONY : JKYi/http/http11_parser.rl.i

# target to preprocess a source file
JKYi/http/http11_parser.rl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http11_parser.rl.cc.i
.PHONY : JKYi/http/http11_parser.rl.cc.i

JKYi/http/http11_parser.rl.s: JKYi/http/http11_parser.rl.cc.s

.PHONY : JKYi/http/http11_parser.rl.s

# target to generate assembly for a file
JKYi/http/http11_parser.rl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http11_parser.rl.cc.s
.PHONY : JKYi/http/http11_parser.rl.cc.s

JKYi/http/http_connection.o: JKYi/http/http_connection.cc.o

.PHONY : JKYi/http/http_connection.o

# target to build an object file
JKYi/http/http_connection.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_connection.cc.o
.PHONY : JKYi/http/http_connection.cc.o

JKYi/http/http_connection.i: JKYi/http/http_connection.cc.i

.PHONY : JKYi/http/http_connection.i

# target to preprocess a source file
JKYi/http/http_connection.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_connection.cc.i
.PHONY : JKYi/http/http_connection.cc.i

JKYi/http/http_connection.s: JKYi/http/http_connection.cc.s

.PHONY : JKYi/http/http_connection.s

# target to generate assembly for a file
JKYi/http/http_connection.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_connection.cc.s
.PHONY : JKYi/http/http_connection.cc.s

JKYi/http/http_parser.o: JKYi/http/http_parser.cc.o

.PHONY : JKYi/http/http_parser.o

# target to build an object file
JKYi/http/http_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_parser.cc.o
.PHONY : JKYi/http/http_parser.cc.o

JKYi/http/http_parser.i: JKYi/http/http_parser.cc.i

.PHONY : JKYi/http/http_parser.i

# target to preprocess a source file
JKYi/http/http_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_parser.cc.i
.PHONY : JKYi/http/http_parser.cc.i

JKYi/http/http_parser.s: JKYi/http/http_parser.cc.s

.PHONY : JKYi/http/http_parser.s

# target to generate assembly for a file
JKYi/http/http_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_parser.cc.s
.PHONY : JKYi/http/http_parser.cc.s

JKYi/http/http_server.o: JKYi/http/http_server.cc.o

.PHONY : JKYi/http/http_server.o

# target to build an object file
JKYi/http/http_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_server.cc.o
.PHONY : JKYi/http/http_server.cc.o

JKYi/http/http_server.i: JKYi/http/http_server.cc.i

.PHONY : JKYi/http/http_server.i

# target to preprocess a source file
JKYi/http/http_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_server.cc.i
.PHONY : JKYi/http/http_server.cc.i

JKYi/http/http_server.s: JKYi/http/http_server.cc.s

.PHONY : JKYi/http/http_server.s

# target to generate assembly for a file
JKYi/http/http_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_server.cc.s
.PHONY : JKYi/http/http_server.cc.s

JKYi/http/http_session.o: JKYi/http/http_session.cc.o

.PHONY : JKYi/http/http_session.o

# target to build an object file
JKYi/http/http_session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_session.cc.o
.PHONY : JKYi/http/http_session.cc.o

JKYi/http/http_session.i: JKYi/http/http_session.cc.i

.PHONY : JKYi/http/http_session.i

# target to preprocess a source file
JKYi/http/http_session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_session.cc.i
.PHONY : JKYi/http/http_session.cc.i

JKYi/http/http_session.s: JKYi/http/http_session.cc.s

.PHONY : JKYi/http/http_session.s

# target to generate assembly for a file
JKYi/http/http_session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/http_session.cc.s
.PHONY : JKYi/http/http_session.cc.s

JKYi/http/httpclient_parser.rl.o: JKYi/http/httpclient_parser.rl.cc.o

.PHONY : JKYi/http/httpclient_parser.rl.o

# target to build an object file
JKYi/http/httpclient_parser.rl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/httpclient_parser.rl.cc.o
.PHONY : JKYi/http/httpclient_parser.rl.cc.o

JKYi/http/httpclient_parser.rl.i: JKYi/http/httpclient_parser.rl.cc.i

.PHONY : JKYi/http/httpclient_parser.rl.i

# target to preprocess a source file
JKYi/http/httpclient_parser.rl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/httpclient_parser.rl.cc.i
.PHONY : JKYi/http/httpclient_parser.rl.cc.i

JKYi/http/httpclient_parser.rl.s: JKYi/http/httpclient_parser.rl.cc.s

.PHONY : JKYi/http/httpclient_parser.rl.s

# target to generate assembly for a file
JKYi/http/httpclient_parser.rl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/httpclient_parser.rl.cc.s
.PHONY : JKYi/http/httpclient_parser.rl.cc.s

JKYi/http/servlet.o: JKYi/http/servlet.cc.o

.PHONY : JKYi/http/servlet.o

# target to build an object file
JKYi/http/servlet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/servlet.cc.o
.PHONY : JKYi/http/servlet.cc.o

JKYi/http/servlet.i: JKYi/http/servlet.cc.i

.PHONY : JKYi/http/servlet.i

# target to preprocess a source file
JKYi/http/servlet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/servlet.cc.i
.PHONY : JKYi/http/servlet.cc.i

JKYi/http/servlet.s: JKYi/http/servlet.cc.s

.PHONY : JKYi/http/servlet.s

# target to generate assembly for a file
JKYi/http/servlet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/servlet.cc.s
.PHONY : JKYi/http/servlet.cc.s

JKYi/http/ws_connection.o: JKYi/http/ws_connection.cc.o

.PHONY : JKYi/http/ws_connection.o

# target to build an object file
JKYi/http/ws_connection.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_connection.cc.o
.PHONY : JKYi/http/ws_connection.cc.o

JKYi/http/ws_connection.i: JKYi/http/ws_connection.cc.i

.PHONY : JKYi/http/ws_connection.i

# target to preprocess a source file
JKYi/http/ws_connection.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_connection.cc.i
.PHONY : JKYi/http/ws_connection.cc.i

JKYi/http/ws_connection.s: JKYi/http/ws_connection.cc.s

.PHONY : JKYi/http/ws_connection.s

# target to generate assembly for a file
JKYi/http/ws_connection.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_connection.cc.s
.PHONY : JKYi/http/ws_connection.cc.s

JKYi/http/ws_server.o: JKYi/http/ws_server.cc.o

.PHONY : JKYi/http/ws_server.o

# target to build an object file
JKYi/http/ws_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_server.cc.o
.PHONY : JKYi/http/ws_server.cc.o

JKYi/http/ws_server.i: JKYi/http/ws_server.cc.i

.PHONY : JKYi/http/ws_server.i

# target to preprocess a source file
JKYi/http/ws_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_server.cc.i
.PHONY : JKYi/http/ws_server.cc.i

JKYi/http/ws_server.s: JKYi/http/ws_server.cc.s

.PHONY : JKYi/http/ws_server.s

# target to generate assembly for a file
JKYi/http/ws_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_server.cc.s
.PHONY : JKYi/http/ws_server.cc.s

JKYi/http/ws_servlet.o: JKYi/http/ws_servlet.cc.o

.PHONY : JKYi/http/ws_servlet.o

# target to build an object file
JKYi/http/ws_servlet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_servlet.cc.o
.PHONY : JKYi/http/ws_servlet.cc.o

JKYi/http/ws_servlet.i: JKYi/http/ws_servlet.cc.i

.PHONY : JKYi/http/ws_servlet.i

# target to preprocess a source file
JKYi/http/ws_servlet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_servlet.cc.i
.PHONY : JKYi/http/ws_servlet.cc.i

JKYi/http/ws_servlet.s: JKYi/http/ws_servlet.cc.s

.PHONY : JKYi/http/ws_servlet.s

# target to generate assembly for a file
JKYi/http/ws_servlet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_servlet.cc.s
.PHONY : JKYi/http/ws_servlet.cc.s

JKYi/http/ws_session.o: JKYi/http/ws_session.cc.o

.PHONY : JKYi/http/ws_session.o

# target to build an object file
JKYi/http/ws_session.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_session.cc.o
.PHONY : JKYi/http/ws_session.cc.o

JKYi/http/ws_session.i: JKYi/http/ws_session.cc.i

.PHONY : JKYi/http/ws_session.i

# target to preprocess a source file
JKYi/http/ws_session.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_session.cc.i
.PHONY : JKYi/http/ws_session.cc.i

JKYi/http/ws_session.s: JKYi/http/ws_session.cc.s

.PHONY : JKYi/http/ws_session.s

# target to generate assembly for a file
JKYi/http/ws_session.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/http/ws_session.cc.s
.PHONY : JKYi/http/ws_session.cc.s

JKYi/iomanager.o: JKYi/iomanager.cc.o

.PHONY : JKYi/iomanager.o

# target to build an object file
JKYi/iomanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/iomanager.cc.o
.PHONY : JKYi/iomanager.cc.o

JKYi/iomanager.i: JKYi/iomanager.cc.i

.PHONY : JKYi/iomanager.i

# target to preprocess a source file
JKYi/iomanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/iomanager.cc.i
.PHONY : JKYi/iomanager.cc.i

JKYi/iomanager.s: JKYi/iomanager.cc.s

.PHONY : JKYi/iomanager.s

# target to generate assembly for a file
JKYi/iomanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/iomanager.cc.s
.PHONY : JKYi/iomanager.cc.s

JKYi/library.o: JKYi/library.cc.o

.PHONY : JKYi/library.o

# target to build an object file
JKYi/library.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/library.cc.o
.PHONY : JKYi/library.cc.o

JKYi/library.i: JKYi/library.cc.i

.PHONY : JKYi/library.i

# target to preprocess a source file
JKYi/library.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/library.cc.i
.PHONY : JKYi/library.cc.i

JKYi/library.s: JKYi/library.cc.s

.PHONY : JKYi/library.s

# target to generate assembly for a file
JKYi/library.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/library.cc.s
.PHONY : JKYi/library.cc.s

JKYi/log.o: JKYi/log.cc.o

.PHONY : JKYi/log.o

# target to build an object file
JKYi/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/log.cc.o
.PHONY : JKYi/log.cc.o

JKYi/log.i: JKYi/log.cc.i

.PHONY : JKYi/log.i

# target to preprocess a source file
JKYi/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/log.cc.i
.PHONY : JKYi/log.cc.i

JKYi/log.s: JKYi/log.cc.s

.PHONY : JKYi/log.s

# target to generate assembly for a file
JKYi/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/log.cc.s
.PHONY : JKYi/log.cc.s

JKYi/module.o: JKYi/module.cc.o

.PHONY : JKYi/module.o

# target to build an object file
JKYi/module.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/module.cc.o
.PHONY : JKYi/module.cc.o

JKYi/module.i: JKYi/module.cc.i

.PHONY : JKYi/module.i

# target to preprocess a source file
JKYi/module.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/module.cc.i
.PHONY : JKYi/module.cc.i

JKYi/module.s: JKYi/module.cc.s

.PHONY : JKYi/module.s

# target to generate assembly for a file
JKYi/module.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/module.cc.s
.PHONY : JKYi/module.cc.s

JKYi/mutex.o: JKYi/mutex.cc.o

.PHONY : JKYi/mutex.o

# target to build an object file
JKYi/mutex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/mutex.cc.o
.PHONY : JKYi/mutex.cc.o

JKYi/mutex.i: JKYi/mutex.cc.i

.PHONY : JKYi/mutex.i

# target to preprocess a source file
JKYi/mutex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/mutex.cc.i
.PHONY : JKYi/mutex.cc.i

JKYi/mutex.s: JKYi/mutex.cc.s

.PHONY : JKYi/mutex.s

# target to generate assembly for a file
JKYi/mutex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/mutex.cc.s
.PHONY : JKYi/mutex.cc.s

JKYi/protocol.o: JKYi/protocol.cc.o

.PHONY : JKYi/protocol.o

# target to build an object file
JKYi/protocol.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/protocol.cc.o
.PHONY : JKYi/protocol.cc.o

JKYi/protocol.i: JKYi/protocol.cc.i

.PHONY : JKYi/protocol.i

# target to preprocess a source file
JKYi/protocol.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/protocol.cc.i
.PHONY : JKYi/protocol.cc.i

JKYi/protocol.s: JKYi/protocol.cc.s

.PHONY : JKYi/protocol.s

# target to generate assembly for a file
JKYi/protocol.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/protocol.cc.s
.PHONY : JKYi/protocol.cc.s

JKYi/scheduler.o: JKYi/scheduler.cc.o

.PHONY : JKYi/scheduler.o

# target to build an object file
JKYi/scheduler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/scheduler.cc.o
.PHONY : JKYi/scheduler.cc.o

JKYi/scheduler.i: JKYi/scheduler.cc.i

.PHONY : JKYi/scheduler.i

# target to preprocess a source file
JKYi/scheduler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/scheduler.cc.i
.PHONY : JKYi/scheduler.cc.i

JKYi/scheduler.s: JKYi/scheduler.cc.s

.PHONY : JKYi/scheduler.s

# target to generate assembly for a file
JKYi/scheduler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/scheduler.cc.s
.PHONY : JKYi/scheduler.cc.s

JKYi/socket.o: JKYi/socket.cc.o

.PHONY : JKYi/socket.o

# target to build an object file
JKYi/socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/socket.cc.o
.PHONY : JKYi/socket.cc.o

JKYi/socket.i: JKYi/socket.cc.i

.PHONY : JKYi/socket.i

# target to preprocess a source file
JKYi/socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/socket.cc.i
.PHONY : JKYi/socket.cc.i

JKYi/socket.s: JKYi/socket.cc.s

.PHONY : JKYi/socket.s

# target to generate assembly for a file
JKYi/socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/socket.cc.s
.PHONY : JKYi/socket.cc.s

JKYi/stream.o: JKYi/stream.cc.o

.PHONY : JKYi/stream.o

# target to build an object file
JKYi/stream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/stream.cc.o
.PHONY : JKYi/stream.cc.o

JKYi/stream.i: JKYi/stream.cc.i

.PHONY : JKYi/stream.i

# target to preprocess a source file
JKYi/stream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/stream.cc.i
.PHONY : JKYi/stream.cc.i

JKYi/stream.s: JKYi/stream.cc.s

.PHONY : JKYi/stream.s

# target to generate assembly for a file
JKYi/stream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/stream.cc.s
.PHONY : JKYi/stream.cc.s

JKYi/stream/socket_stream.o: JKYi/stream/socket_stream.cc.o

.PHONY : JKYi/stream/socket_stream.o

# target to build an object file
JKYi/stream/socket_stream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/stream/socket_stream.cc.o
.PHONY : JKYi/stream/socket_stream.cc.o

JKYi/stream/socket_stream.i: JKYi/stream/socket_stream.cc.i

.PHONY : JKYi/stream/socket_stream.i

# target to preprocess a source file
JKYi/stream/socket_stream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/stream/socket_stream.cc.i
.PHONY : JKYi/stream/socket_stream.cc.i

JKYi/stream/socket_stream.s: JKYi/stream/socket_stream.cc.s

.PHONY : JKYi/stream/socket_stream.s

# target to generate assembly for a file
JKYi/stream/socket_stream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/stream/socket_stream.cc.s
.PHONY : JKYi/stream/socket_stream.cc.s

JKYi/tcp_server.o: JKYi/tcp_server.cc.o

.PHONY : JKYi/tcp_server.o

# target to build an object file
JKYi/tcp_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/tcp_server.cc.o
.PHONY : JKYi/tcp_server.cc.o

JKYi/tcp_server.i: JKYi/tcp_server.cc.i

.PHONY : JKYi/tcp_server.i

# target to preprocess a source file
JKYi/tcp_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/tcp_server.cc.i
.PHONY : JKYi/tcp_server.cc.i

JKYi/tcp_server.s: JKYi/tcp_server.cc.s

.PHONY : JKYi/tcp_server.s

# target to generate assembly for a file
JKYi/tcp_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/tcp_server.cc.s
.PHONY : JKYi/tcp_server.cc.s

JKYi/thread.o: JKYi/thread.cc.o

.PHONY : JKYi/thread.o

# target to build an object file
JKYi/thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/thread.cc.o
.PHONY : JKYi/thread.cc.o

JKYi/thread.i: JKYi/thread.cc.i

.PHONY : JKYi/thread.i

# target to preprocess a source file
JKYi/thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/thread.cc.i
.PHONY : JKYi/thread.cc.i

JKYi/thread.s: JKYi/thread.cc.s

.PHONY : JKYi/thread.s

# target to generate assembly for a file
JKYi/thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/thread.cc.s
.PHONY : JKYi/thread.cc.s

JKYi/timer.o: JKYi/timer.cc.o

.PHONY : JKYi/timer.o

# target to build an object file
JKYi/timer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/timer.cc.o
.PHONY : JKYi/timer.cc.o

JKYi/timer.i: JKYi/timer.cc.i

.PHONY : JKYi/timer.i

# target to preprocess a source file
JKYi/timer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/timer.cc.i
.PHONY : JKYi/timer.cc.i

JKYi/timer.s: JKYi/timer.cc.s

.PHONY : JKYi/timer.s

# target to generate assembly for a file
JKYi/timer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/timer.cc.s
.PHONY : JKYi/timer.cc.s

JKYi/uri.rl.o: JKYi/uri.rl.cc.o

.PHONY : JKYi/uri.rl.o

# target to build an object file
JKYi/uri.rl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/uri.rl.cc.o
.PHONY : JKYi/uri.rl.cc.o

JKYi/uri.rl.i: JKYi/uri.rl.cc.i

.PHONY : JKYi/uri.rl.i

# target to preprocess a source file
JKYi/uri.rl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/uri.rl.cc.i
.PHONY : JKYi/uri.rl.cc.i

JKYi/uri.rl.s: JKYi/uri.rl.cc.s

.PHONY : JKYi/uri.rl.s

# target to generate assembly for a file
JKYi/uri.rl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/uri.rl.cc.s
.PHONY : JKYi/uri.rl.cc.s

JKYi/util.o: JKYi/util.cc.o

.PHONY : JKYi/util.o

# target to build an object file
JKYi/util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/util.cc.o
.PHONY : JKYi/util.cc.o

JKYi/util.i: JKYi/util.cc.i

.PHONY : JKYi/util.i

# target to preprocess a source file
JKYi/util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/util.cc.i
.PHONY : JKYi/util.cc.i

JKYi/util.s: JKYi/util.cc.s

.PHONY : JKYi/util.s

# target to generate assembly for a file
JKYi/util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/util.cc.s
.PHONY : JKYi/util.cc.s

JKYi/worker.o: JKYi/worker.cc.o

.PHONY : JKYi/worker.o

# target to build an object file
JKYi/worker.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/worker.cc.o
.PHONY : JKYi/worker.cc.o

JKYi/worker.i: JKYi/worker.cc.i

.PHONY : JKYi/worker.i

# target to preprocess a source file
JKYi/worker.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/worker.cc.i
.PHONY : JKYi/worker.cc.i

JKYi/worker.s: JKYi/worker.cc.s

.PHONY : JKYi/worker.s

# target to generate assembly for a file
JKYi/worker.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JKYi.dir/build.make CMakeFiles/JKYi.dir/JKYi/worker.cc.s
.PHONY : JKYi/worker.cc.s

sample/my_http_server.o: sample/my_http_server.cc.o

.PHONY : sample/my_http_server.o

# target to build an object file
sample/my_http_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/sample/my_http_server.cc.o
.PHONY : sample/my_http_server.cc.o

sample/my_http_server.i: sample/my_http_server.cc.i

.PHONY : sample/my_http_server.i

# target to preprocess a source file
sample/my_http_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/sample/my_http_server.cc.i
.PHONY : sample/my_http_server.cc.i

sample/my_http_server.s: sample/my_http_server.cc.s

.PHONY : sample/my_http_server.s

# target to generate assembly for a file
sample/my_http_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/sample/my_http_server.cc.s
.PHONY : sample/my_http_server.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_address.o: tests/test_address.cc.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.o
.PHONY : tests/test_address.cc.o

tests/test_address.i: tests/test_address.cc.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.i
.PHONY : tests/test_address.cc.i

tests/test_address.s: tests/test_address.cc.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.s
.PHONY : tests/test_address.cc.s

tests/test_application.o: tests/test_application.cc.o

.PHONY : tests/test_application.o

# target to build an object file
tests/test_application.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/tests/test_application.cc.o
.PHONY : tests/test_application.cc.o

tests/test_application.i: tests/test_application.cc.i

.PHONY : tests/test_application.i

# target to preprocess a source file
tests/test_application.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/tests/test_application.cc.i
.PHONY : tests/test_application.cc.i

tests/test_application.s: tests/test_application.cc.s

.PHONY : tests/test_application.s

# target to generate assembly for a file
tests/test_application.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_application.dir/build.make CMakeFiles/test_application.dir/tests/test_application.cc.s
.PHONY : tests/test_application.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_daemon.o: tests/test_daemon.cc.o

.PHONY : tests/test_daemon.o

# target to build an object file
tests/test_daemon.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/tests/test_daemon.cc.o
.PHONY : tests/test_daemon.cc.o

tests/test_daemon.i: tests/test_daemon.cc.i

.PHONY : tests/test_daemon.i

# target to preprocess a source file
tests/test_daemon.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/tests/test_daemon.cc.i
.PHONY : tests/test_daemon.cc.i

tests/test_daemon.s: tests/test_daemon.cc.s

.PHONY : tests/test_daemon.s

# target to generate assembly for a file
tests/test_daemon.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_daemon.dir/build.make CMakeFiles/test_daemon.dir/tests/test_daemon.cc.s
.PHONY : tests/test_daemon.cc.s

tests/test_env.o: tests/test_env.cc.o

.PHONY : tests/test_env.o

# target to build an object file
tests/test_env.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/tests/test_env.cc.o
.PHONY : tests/test_env.cc.o

tests/test_env.i: tests/test_env.cc.i

.PHONY : tests/test_env.i

# target to preprocess a source file
tests/test_env.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/tests/test_env.cc.i
.PHONY : tests/test_env.cc.i

tests/test_env.s: tests/test_env.cc.s

.PHONY : tests/test_env.s

# target to generate assembly for a file
tests/test_env.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_env.dir/build.make CMakeFiles/test_env.dir/tests/test_env.cc.s
.PHONY : tests/test_env.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_http.o: tests/test_http.cc.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.o
.PHONY : tests/test_http.cc.o

tests/test_http.i: tests/test_http.cc.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.i
.PHONY : tests/test_http.cc.i

tests/test_http.s: tests/test_http.cc.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.s
.PHONY : tests/test_http.cc.s

tests/test_http_connection.o: tests/test_http_connection.cc.o

.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.o
.PHONY : tests/test_http_connection.cc.o

tests/test_http_connection.i: tests/test_http_connection.cc.i

.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.i
.PHONY : tests/test_http_connection.cc.i

tests/test_http_connection.s: tests/test_http_connection.cc.s

.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.s
.PHONY : tests/test_http_connection.cc.s

tests/test_http_parser.o: tests/test_http_parser.cc.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.o
.PHONY : tests/test_http_parser.cc.o

tests/test_http_parser.i: tests/test_http_parser.cc.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.i
.PHONY : tests/test_http_parser.cc.i

tests/test_http_parser.s: tests/test_http_parser.cc.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.s
.PHONY : tests/test_http_parser.cc.s

tests/test_http_server.o: tests/test_http_server.cc.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.o
.PHONY : tests/test_http_server.cc.o

tests/test_http_server.i: tests/test_http_server.cc.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.i
.PHONY : tests/test_http_server.cc.i

tests/test_http_server.s: tests/test_http_server.cc.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.s
.PHONY : tests/test_http_server.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

tests/test_ws_client.o: tests/test_ws_client.cc.o

.PHONY : tests/test_ws_client.o

# target to build an object file
tests/test_ws_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_client.dir/build.make CMakeFiles/test_ws_client.dir/tests/test_ws_client.cc.o
.PHONY : tests/test_ws_client.cc.o

tests/test_ws_client.i: tests/test_ws_client.cc.i

.PHONY : tests/test_ws_client.i

# target to preprocess a source file
tests/test_ws_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_client.dir/build.make CMakeFiles/test_ws_client.dir/tests/test_ws_client.cc.i
.PHONY : tests/test_ws_client.cc.i

tests/test_ws_client.s: tests/test_ws_client.cc.s

.PHONY : tests/test_ws_client.s

# target to generate assembly for a file
tests/test_ws_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_client.dir/build.make CMakeFiles/test_ws_client.dir/tests/test_ws_client.cc.s
.PHONY : tests/test_ws_client.cc.s

tests/test_ws_server.o: tests/test_ws_server.cc.o

.PHONY : tests/test_ws_server.o

# target to build an object file
tests/test_ws_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_server.dir/build.make CMakeFiles/test_ws_server.dir/tests/test_ws_server.cc.o
.PHONY : tests/test_ws_server.cc.o

tests/test_ws_server.i: tests/test_ws_server.cc.i

.PHONY : tests/test_ws_server.i

# target to preprocess a source file
tests/test_ws_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_server.dir/build.make CMakeFiles/test_ws_server.dir/tests/test_ws_server.cc.i
.PHONY : tests/test_ws_server.cc.i

tests/test_ws_server.s: tests/test_ws_server.cc.s

.PHONY : tests/test_ws_server.s

# target to generate assembly for a file
tests/test_ws_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ws_server.dir/build.make CMakeFiles/test_ws_server.dir/tests/test_ws_server.cc.s
.PHONY : tests/test_ws_server.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_address"
	@echo "... test_iomanager"
	@echo "... test_scheduler"
	@echo "... JKYi"
	@echo "... my_http_server"
	@echo "... test_ws_client"
	@echo "... test_fiber"
	@echo "... test_http_connection"
	@echo "... test_hook"
	@echo "... test_env"
	@echo "... test_util"
	@echo "... edit_cache"
	@echo "... test_application"
	@echo "... test_http_server"
	@echo "... test_thread"
	@echo "... test_config"
	@echo "... test_socket"
	@echo "... test"
	@echo "... test_http"
	@echo "... test_ws_server"
	@echo "... test_bytearray"
	@echo "... test_http_parser"
	@echo "... test_daemon"
	@echo "... JKYi/address.o"
	@echo "... JKYi/address.i"
	@echo "... JKYi/address.s"
	@echo "... JKYi/application.o"
	@echo "... JKYi/application.i"
	@echo "... JKYi/application.s"
	@echo "... JKYi/bytearray.o"
	@echo "... JKYi/bytearray.i"
	@echo "... JKYi/bytearray.s"
	@echo "... JKYi/config.o"
	@echo "... JKYi/config.i"
	@echo "... JKYi/config.s"
	@echo "... JKYi/daemon.o"
	@echo "... JKYi/daemon.i"
	@echo "... JKYi/daemon.s"
	@echo "... JKYi/env.o"
	@echo "... JKYi/env.i"
	@echo "... JKYi/env.s"
	@echo "... JKYi/fdmanager.o"
	@echo "... JKYi/fdmanager.i"
	@echo "... JKYi/fdmanager.s"
	@echo "... JKYi/fiber.o"
	@echo "... JKYi/fiber.i"
	@echo "... JKYi/fiber.s"
	@echo "... JKYi/hook.o"
	@echo "... JKYi/hook.i"
	@echo "... JKYi/hook.s"
	@echo "... JKYi/http/http.o"
	@echo "... JKYi/http/http.i"
	@echo "... JKYi/http/http.s"
	@echo "... JKYi/http/http11_parser.rl.o"
	@echo "... JKYi/http/http11_parser.rl.i"
	@echo "... JKYi/http/http11_parser.rl.s"
	@echo "... JKYi/http/http_connection.o"
	@echo "... JKYi/http/http_connection.i"
	@echo "... JKYi/http/http_connection.s"
	@echo "... JKYi/http/http_parser.o"
	@echo "... JKYi/http/http_parser.i"
	@echo "... JKYi/http/http_parser.s"
	@echo "... JKYi/http/http_server.o"
	@echo "... JKYi/http/http_server.i"
	@echo "... JKYi/http/http_server.s"
	@echo "... JKYi/http/http_session.o"
	@echo "... JKYi/http/http_session.i"
	@echo "... JKYi/http/http_session.s"
	@echo "... JKYi/http/httpclient_parser.rl.o"
	@echo "... JKYi/http/httpclient_parser.rl.i"
	@echo "... JKYi/http/httpclient_parser.rl.s"
	@echo "... JKYi/http/servlet.o"
	@echo "... JKYi/http/servlet.i"
	@echo "... JKYi/http/servlet.s"
	@echo "... JKYi/http/ws_connection.o"
	@echo "... JKYi/http/ws_connection.i"
	@echo "... JKYi/http/ws_connection.s"
	@echo "... JKYi/http/ws_server.o"
	@echo "... JKYi/http/ws_server.i"
	@echo "... JKYi/http/ws_server.s"
	@echo "... JKYi/http/ws_servlet.o"
	@echo "... JKYi/http/ws_servlet.i"
	@echo "... JKYi/http/ws_servlet.s"
	@echo "... JKYi/http/ws_session.o"
	@echo "... JKYi/http/ws_session.i"
	@echo "... JKYi/http/ws_session.s"
	@echo "... JKYi/iomanager.o"
	@echo "... JKYi/iomanager.i"
	@echo "... JKYi/iomanager.s"
	@echo "... JKYi/library.o"
	@echo "... JKYi/library.i"
	@echo "... JKYi/library.s"
	@echo "... JKYi/log.o"
	@echo "... JKYi/log.i"
	@echo "... JKYi/log.s"
	@echo "... JKYi/module.o"
	@echo "... JKYi/module.i"
	@echo "... JKYi/module.s"
	@echo "... JKYi/mutex.o"
	@echo "... JKYi/mutex.i"
	@echo "... JKYi/mutex.s"
	@echo "... JKYi/protocol.o"
	@echo "... JKYi/protocol.i"
	@echo "... JKYi/protocol.s"
	@echo "... JKYi/scheduler.o"
	@echo "... JKYi/scheduler.i"
	@echo "... JKYi/scheduler.s"
	@echo "... JKYi/socket.o"
	@echo "... JKYi/socket.i"
	@echo "... JKYi/socket.s"
	@echo "... JKYi/stream.o"
	@echo "... JKYi/stream.i"
	@echo "... JKYi/stream.s"
	@echo "... JKYi/stream/socket_stream.o"
	@echo "... JKYi/stream/socket_stream.i"
	@echo "... JKYi/stream/socket_stream.s"
	@echo "... JKYi/tcp_server.o"
	@echo "... JKYi/tcp_server.i"
	@echo "... JKYi/tcp_server.s"
	@echo "... JKYi/thread.o"
	@echo "... JKYi/thread.i"
	@echo "... JKYi/thread.s"
	@echo "... JKYi/timer.o"
	@echo "... JKYi/timer.i"
	@echo "... JKYi/timer.s"
	@echo "... JKYi/uri.rl.o"
	@echo "... JKYi/uri.rl.i"
	@echo "... JKYi/uri.rl.s"
	@echo "... JKYi/util.o"
	@echo "... JKYi/util.i"
	@echo "... JKYi/util.s"
	@echo "... JKYi/worker.o"
	@echo "... JKYi/worker.i"
	@echo "... JKYi/worker.s"
	@echo "... sample/my_http_server.o"
	@echo "... sample/my_http_server.i"
	@echo "... sample/my_http_server.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_application.o"
	@echo "... tests/test_application.i"
	@echo "... tests/test_application.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_daemon.o"
	@echo "... tests/test_daemon.i"
	@echo "... tests/test_daemon.s"
	@echo "... tests/test_env.o"
	@echo "... tests/test_env.i"
	@echo "... tests/test_env.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
	@echo "... tests/test_ws_client.o"
	@echo "... tests/test_ws_client.i"
	@echo "... tests/test_ws_client.s"
	@echo "... tests/test_ws_server.o"
	@echo "... tests/test_ws_server.i"
	@echo "... tests/test_ws_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

